version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=es-cluster-7
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200


  kibana:
    image: docker.elastic.co/kibana/kibana:7.11.1
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - 5601:5601

    depends_on:
      - elasticsearch

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.5
    container_name: logstash
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf 
      - ./mssql-jdbc-12.6.1.jre8.jar:/usr/share/logstash/mssql-jdbc-12.6.1.jre8.jar
    depends_on:
      - elasticsearch
    ports:
      - "5044:5044"
    environment:
      - "LS_JAVA_OPTS=-Djava.library.path=/usr/share/logstash"
    command: logstash -f /usr/share/logstash/pipeline/logstash.conf

volumes:
  es-data01:
    driver: local

